# Site settings
title: Kevin Hou's Blog
author: Kevin Hou
location: San Francisco Bay Area
school: Lick-Wilmerding High School
email: kevin.ch.hou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming, wood, and anything that comes to my mind. Enjoy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khou22.github.io" # the base hostname & protocol for your site
twitter_username: kevinhou22
github_username:  khou22
LinkedIn_url: "https://www.linkedin.com/in/kevinhou22"
portfolio_url: "http://kevinhou.wix.com/projects"
youtube_url: "https://youtube.com/kevinhou22"
flickr_url: "https://www.flickr.com/photos/khou22/albums"
school_profile: "https://www.princeton.edu/main/"

# Build settings
markdown: kramdown

# Bug fixes
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
